// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4--4QHKQnlX_xGV0afsXVaPN83QiZCSk',
    appId: '1:255773976678:web:02c670136815ead53525a7',
    messagingSenderId: '255773976678',
    projectId: 'fir-flutter-app-115ef',
    authDomain: 'fir-flutter-app-115ef.firebaseapp.com',
    storageBucket: 'fir-flutter-app-115ef.appspot.com',
    measurementId: 'G-83SDNKZW4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmWvH-jzTP4AtZJG2shruIEkOWz6RnKLY',
    appId: '1:255773976678:android:fd369d7919983c603525a7',
    messagingSenderId: '255773976678',
    projectId: 'fir-flutter-app-115ef',
    storageBucket: 'fir-flutter-app-115ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2nncMphCTkPRNbcYyrYLr8OaJm-LR38',
    appId: '1:255773976678:ios:231bc34fdce053d23525a7',
    messagingSenderId: '255773976678',
    projectId: 'fir-flutter-app-115ef',
    storageBucket: 'fir-flutter-app-115ef.appspot.com',
    iosClientId: '255773976678-406mqc95usgg4ts5tvnp9iep0lnqoppa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2nncMphCTkPRNbcYyrYLr8OaJm-LR38',
    appId: '1:255773976678:ios:678c5b9f1f2d911f3525a7',
    messagingSenderId: '255773976678',
    projectId: 'fir-flutter-app-115ef',
    storageBucket: 'fir-flutter-app-115ef.appspot.com',
    iosClientId: '255773976678-0e13u3g97ue9s69l0i2iu4ki6t4qiaq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
